#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not govern POSIX compliant, you may need to use /bin/bash or /bin/ksh.
#
#   (2) Put the JDK directory in your environment variable JAVA_HOME.
#
##############################################################################

PROG="$0"
# Need this for relative symlinks.
while [ -h "$PROG" ] ; do
    ls=`ls -ld "$PROG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PROG="$link"
    else
        PROG=`dirname "$PROG"`"/$link"
    fi
done

savedir=`pwd`
cd "`dirname \"$PROG\"`" >/dev/null
PROG="`pwd`/`basename \"$PROG\"`"
cd "$savedir"

GRADLE_HOME=`dirname "$PROG"`/gradle
export GRADLE_HOME
PATH="$GRADLE_HOME/bin:$PATH"
export PATH

exec "$GRADLE_HOME/bin/gradle" "$@"
